Miyu01
RinKokubo/team3-app pull request #13
Opened 2023-06-21 07:56 UTC by miyu-betty

10F/11F

2023-06-21 10:34 UTC, RinKokubo requested changes

2023-06-21 10:34 UTC, RinKokubo commented on src/components/10thFloor.vue
> +          <p>現在３Fで実施されている授業はありません。</p>
ここも修正お願いします！

2023-06-21 10:34 UTC, RinKokubo commented on src/components/11thFloor.vue
> +          <p>現在３Fで実施されている授業はありません。</p>
ここも！

2023-06-27 16:39 UTC, miyu-betty commented
修正しました

2023-06-28 06:18 UTC, RinKokubo approved these changes

2023-06-28 06:18 UTC, RinKokubo approved these changes

2023-06-28 06:18 UTC, merged